#!/usr/bin/bash

KERNEL_FILE="$1"
UKI_FILE="$3"

if [ ! -f /usr/share/secureboot/keys/db/db.pem ]; then
    echo "No keys found for signing"
    exit 0
fi

IMAGE_FILE="$KERNEL_FILE"
if [ -n "$KERNELDESTINATION" ] && [ -f "$KERNELDESTINATION" ]; then
    IMAGE_FILE="$KERNELDESTINATION"
fi
if [ -n "$UKI_FILE" ]; then
    IMAGE_FILE="$UKI_FILE"
fi

if [ -z "$IMAGE_FILE" ]; then
    echo "No kernel or UKI found for signing"
    exit 0
fi

echo "Signing $IMAGE_FILE"
sbctl sign -s "$IMAGE_FILE"
